version: '3.7'
services:
  kvb-api:
    image: kvb-api:latest
    container_name: kvb-api
    ports:
      - 8080:8080
    environment:
      - ENABLE_TRACING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317
      # Can be enabled to debug trace sending
      # - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info 
